### PR TITLE
fix(ui): handle empty spoiler text

### LINKED ISSUE #2090: Elk shows "Media hidden" but there is no media to show
In this post https://elk.zone/mastodon.social/@Pwnallthethings/110341838593089566 , Elk shows info about hidden media, however the post does not have any media to show.

The following images shows hos Elk renders the post.

Without klicking "Media hidden":
elk1

When klicking "Media hidden":
elk2

### PR DESCRIPTION
**Pull request by userquin**
It seems some servers sending empty expoiler text.

closes #2090

imagen

### CODE REVIEW

File: components/status/StatusContent.vue [hunk 1]
```diff
@@ -21,7 +21,8 @@ const isFiltered = $computed(() => status.account.id !== currentUser.value?.acco
 
 // check spoiler text or media attachment
 // needed to handle accounts that mark all their posts as sensitive
-const hasSpoilerOrSensitiveMedia = $computed(() => !!status.spoilerText || (status.sensitive && !!status.mediaAttachments.length))
+const spoilerTextPresent = $computed(() => !!status.spoilerText && status.spoilerText.trim().length === 0)
```
Comment (userquin) [inline components/status/StatusContent.vue:24]: upps this is worng
