### PR TITLE
fix: paginator values being cloned

### LINKED ISSUE #3431: Empty statuses shown on profile timeline
Originally reported in #3430 

https://github.com/user-attachments/assets/bfd3704c-75e7-4e86-80fb-7cd51734fbe6

## How to reproduce

1. Open https://elk.zone/m.webtoo.ls/@elkdev@universeodon.com
2. Start scrolling up and down
3. See empty spaces

### PR DESCRIPTION
**Pull request by ayo-run**
fixes #3431 
Prevent paginator values being cloned

Please test the deployed preview: https://deploy-preview-3433--elk-zone.netlify.app/home

## recording
[Screencast from 11-22-2025 06:53:30 PM.webm](https://github.com/user-attachments/assets/540ca28d-e78a-4eb1-b7ad-d1925c703f17)

### CODE REVIEW

**Review by ayoayco — COMMENTED** [review]
In two instances, I extracted `paginator.values()` from loops to prevent it being cloned

File: app/composables/masto/notification.ts [hunk 1]
```diff
@@ -45,9 +45,10 @@ export function useNotifications() {
 
     const position = await client.value.v1.markers.fetch({ timeline: ['notifications'] })
     const paginator = client.value.v1.notifications.list({ limit: 30 })
+    const paginatorValues = paginator.values()
 
     do {
-      const result = await paginator.next()
+      const result = await paginatorValues.next()
```
Comment (ayoayco) [inline app/composables/masto/notification.ts]: Here, I moved out paginator.values() of the do-while loop

**Review by ayoayco — COMMENTED** [review]
In two instances, I extracted paginator.values() from logic that cause it to be cloned unnecessarily

**Review by shuuji3 — APPROVED** [review]
OK, those issues have been solved now (with/without Virtual scroller). Two additional reviewers confirmed the fix in #3431 :+1:
