### PR TITLE
fix(ui): change status actions title

### LINKED ISSUE #2716: bookmark button title not changing
The hover text for the post bookmark button doesn’t change when a post is already bookmarked: from discord server https://discord.com/channels/1044887051155292200/1044887051155292203/1223342234062032997

### PR DESCRIPTION
**Pull request by userquin**
This PR updates the status action title for:
- boost
- favorite
- bookmark

closes #2716

### CODE REVIEW

File: components/status/StatusActions.vue [hunk 1]
```diff
@@ -55,7 +55,7 @@ function reply() {
 
     <div flex-1>
       <StatusActionButton
-        :content="$t('action.boost')"
+        :content="$t(!!status.reblogged ? 'action.boosted' : 'action.boost')"
```
Comment (patak-dev) [inline components/status/StatusActions.vue:58]: You can remove the `!!` from these conditions

Comment (userquin) [reply components/status/StatusActions.vue:58]: sure

Comment (userquin) [reply components/status/StatusActions.vue:58]: check ` :active="!!status.bookmarked"`

**Review by patak-dev — APPROVED** [review]
