### PR TITLE
fix(a11y): make the bottom menu button focusable and navigable with a11y label

### LINKED ISSUE #1422: Accessibility: Unlabeled links
When using a screen reader the statusbar links just read as "link", "link", "link", "link" and the last link will not focus at all.
Screenshot_20230124-102351_Fennec
Screenshot_20230124-102359_Fennec
Screenshot_20230124-102403_Fennec
Screenshot_20230124-102411_Fennec

### PR DESCRIPTION
**Pull request by shuuji3**
fix #1422 

Hi, this is the follow-up PR of #1867

This changes the `<label>` to `<button>` so that users can focus on it and also can open the menu panel by Enter/Space key. I think this doesn't change anything visually.

I'm not sure why the original invisible `<input>` was needed for the click event (I guess it could be attached to `<label>` too?). I believe the same functionality is available now via the `<button>`'s click event so removed it.

**Before**
Screenshot 2023-07-21 at 16 47 27

**After**
Screenshot 2023-07-21 at 16 46 58

Ideally, we can improve the menu items by following the appropriate ARIA menu role coding guide (ARIA: menu role - Accessibility | MDN - https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menu_role) so that those who use accessibility tool can operate the menu more easily. But it requires more detailed work so I'll leave it for future work.

### CODE REVIEW

File: components/nav/NavBottom.vue [hunk 1]
```diff
@@ -43,14 +43,15 @@ const { notifications } = useNotifications()
...
-      <label
+      <button
         flex items-center place-content-center h-full flex-1 class="select-none"
         :class="show ? '!text-primary' : ''"
+        aria-label="More menu"
+        @click="toggleVisible"
       >
-        <input type="checkbox" z="-1" absolute inset-0 opacity-0 @click="toggleVisible">
         <span v-show="show" i-ri:close-fill />
         <span v-show="!show" i-ri:more-fill />
```
Comment (userquin) [inline components/nav/NavBottom.vue:53]: can you replace spans with `<span :class="show ? 'i-ri:close-fill' : 'i-ri:more-fill' />"`

Comment (shuuji3) [reply components/nav/NavBottom.vue]: Thanks, this is a good refactoring. Applied now.

Comment (userquin) [reply components/nav/NavBottom.vue]: remove trailing double quote

File: components/nav/NavBottom.vue [hunk 2]
```diff
@@ -43,14 +43,14 @@ const { notifications } = useNotifications()
...
         flex items-center place-content-center h-full flex-1 class="select-none"
         :class="show ? '!text-primary' : ''"
+        aria-label="More menu"
+        @click="toggleVisible"
       >
-        <input type="checkbox" z="-1" absolute inset-0 opacity-0 @click="toggleVisible">
-        <span v-show="show" i-ri:close-fill />
-        <span v-show="!show" i-ri:more-fill />
-      </label>
+        <span :class="show ? 'i-ri:close-fill' : 'i-ri:more-fill' />"
```
Comment (userquin) [inline components/nav/NavBottom.vue:52]: `<span :class="show ? 'i-ri:close-fill' : 'i-ri:more-fill'" />`

The trailing `"`  is outside the span tag

Comment (userquin) [reply components/nav/NavBottom.vue:52]: My snippet was wrong, sorry man

Comment (shuuji3) [reply components/nav/NavBottom.vue]: Ah, that's why.😄 No problem, it was helpful and should be fixed now.

**Review by userquin — APPROVED** [review]
