### PR TITLE
fix(cache): return cached account as promise

### LINKED ISSUE #2601: User profile panel is not shown when hovering
Tested version: Canary (https://github.com/elk-zone/elk/commit/b9394c2fa54d3899dd79bcc808cfc2af4245c144)

When hovering on the `@username` link, it doesn't show the profile panel but console log the following error:

Screenshot from 2024-02-22 00-12-27

```js
entry.1f2092ce.js:1 TypeError: Cannot read properties of undefined (reading 'includes')
    at Fa (entry.1f2092ce.js:8:13373)
    at sl (entry.1f2092ce.js:8:13539)
    at qs (entry.1f2092ce.js:8:13749)
    at Proxy.<anonymous> (entry.1f2092ce.js:52:16681)
    at vl (entry.1f2092ce.js:1:17142)
    at wu.z [as fn] (entry.1f2092ce.js:1:52929)
    at wu.run (entry.1f2092ce.js:1:4872)
    at U.b.update (entry.1f2092ce.js:1:53208)
    at U (entry.1f2092ce.js:1:53234)
    at ee (entry.1f2092ce.js:1:52047)
```

### PR DESCRIPTION
**Pull request by userquin**

### CODE REVIEW

File: composables/cache.ts [hunk 1]
```diff
@@ -26,23 +25,12 @@ export function fetchStatus(id: string, force = false): Promise<mastodon.v1.Stat
...
-
-  const promise = new Promise<any>((resolve) => {
-    fetchPromise!.then(resolve)
-  })
-  if (!cache.has(key) || force)
-    cache.set(key, promise)
-
+  const promise = useMastoClient().v1.statuses.$select(id).fetch()
+    .then((status) => {
+      cacheStatus(status)
```
Comment (patak-dev) [inline composables/cache.ts:30]: This is a bit confusing. Is it really needed for the `key` to be recalculated? Couldn't we directly call `cache.set(key, status)` here?

Comment (userquin) [reply composables/cache.ts:30]: We register 2 things there... the code is the original,  we can chabge it but the code will be duplicated

File: composables/cache.ts [hunk 2]
```diff
@@ -57,27 +45,16 @@ export function fetchAccountById(id?: string | null): Promise<mastodon.v1.Accoun
...
-  if (!cache.has(key))
-    cache.set(key, promise)
-
+  const domain = getInstanceDomainFromServer(server)
+  const promise = useMastoClient().v1.accounts.$select(id).fetch()
+    .then((r) => {
+      if (r.acct && !r.acct.includes('@') && domain)
+        r.acct = `${r.acct}@${domain}`
+
+      cacheAccount(r, server, true)
```
Comment (patak-dev) [inline composables/cache.ts:54]: Same here, but this one seems to be doing more. It may be good to call `cache.set(key, r)` here and then do whatever else `cacheAccount` does in a separate function. We could do that in another PR though.

File: composables/cache.ts [hunk 3]
```diff
@@ -106,23 +83,13 @@ export async function fetchAccountByHandle(acct: string): Promise<mastodon.v1.Ac
...
-
-  const promise = new Promise<any>((resolve) => {
-    fetchPromise!.then(resolve)
-  })
-  if (!cache.has(key))
-    cache.set(key, promise)
 
+  const promise = lookupAccount()
+    .then((r) => {
+      cacheAccount(r, server, true)
```
Comment (patak-dev) [inline composables/cache.ts:89]: Same here. I think it is important that we make sure the `key` is the same, so we don't leave any promises in the cache.

File: composables/cache.ts (hunk 2 above)
Comment (userquin) [reply composables/cache.ts:54]: This pr is about to fix the return on these 3 methods,  should return a promise to avoid errors like `.then not found`

Comment (userquin) [reply composables/cache.ts:54]: I can send a pr tmr to includeyour suggestions

Comment (patak-dev) [reply composables/cache.ts:54]: Ah, it seems I was looking at a previous commit

**Review by patak-dev — APPROVED** [review]
