### PR TITLE
fix: should hide tooltip when click outside

### LINKED ISSUE #1062: Toolip not hide when click elsewhere.
### Pre-Checks

- [X] Check that there isn't [already an issue](https://github.com/elk-zone/elk/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/elk-zone/elk/discussions) or join our [Discord Chat Server](https://chat.elk.zone).
- [X] Providing a screenshot or video to reproduce the issue or show visually what was meant.
- [ ] I am willing to provide a PR.

### Describe the bug

We click emoji icon, tooltip shows, that's good. But when click somewhere else, tooltip did't hide.

### Reproduction video or screenshot

https://user-images.githubusercontent.com/49969959/212295135-d8b0eff3-7388-4c1a-8b16-d19e6d4d361b.mp4

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by webfansplz**
Closes #1062

### CODE REVIEW

**Comment by edimitchel** [comment]
This should normally not be needed.
I think we need some @Akryum advice or confirmation it's a bug?

**Comment by webfansplz** [comment]
> By default tooltips close on mouse out or blur, you shouldn't have to add this logic. Also if you really need it, just put `autoHide`

Thanks.

**Comment by webfansplz** [comment]
> This should normally not be needed. I think we need some @Akryum advice or confirmation it's a bug?

For #1062, it might make sense to add `autoHide`.

**Review by antfu — APPROVED** [review]

**Review by edimitchel — APPROVED** [review]

File: components/common/CommonTooltip.vue [hunk 1]
```diff
@@ -9,6 +9,7 @@ defineProps<{
 <template>
   <VTooltip
     v-bind="$attrs"
+    :auto-hide="true"
```
Comment (edimitchel) [inline components/common/CommonTooltip.vue:12]:
```suggestion
    auto-hide
```

**Review by edimitchel — CHANGES_REQUESTED** [review]
